// Global Bulgarian → English vocabulary for word-hover tooltips.
// Keys are lowercase Bulgarian words (without punctuation).
// Used by BulgarianSentence as a fallback when no exercise-specific hint covers a word.
export const VOCAB = {
  // Common grammar words
  'е': 'is',
  'и': 'and',
  'в': 'in / on',
  'за': 'for',
  'не': 'not / no',
  'ли': '(question word)',
  'на': 'to / of',
  'до': 'to / until',
  'от': 'from',
  'с': 'with',
  'но': 'but',
  'или': 'or',
  'само': 'only',
  'тук': 'here',
  'там': 'there',
  'как': 'how',
  'какво': 'what',
  'кой': 'who / which',
  'кога': 'when',
  'колко': 'how much / how many',
  'ще': 'will',
  'може': 'can / may',
  'трябва': 'must / need to',
  'много': 'very / a lot',
  'малко': 'a little / few',
  'вече': 'already',
  'още': 'still / more',
  'това': 'this',
  'това': 'this',
  'аз': 'I',
  'ти': 'you (informal)',
  'той': 'he',
  'тя': 'she',
  'то': 'it',
  'ние': 'we',
  'вие': 'you (formal/plural)',
  'те': 'they',

  // Greetings & basics
  'здравей': 'hello (informal)',
  'здравейте': 'hello (formal/plural)',
  'довиждане': 'goodbye',
  'чао': 'bye',
  'добре': 'fine / well',
  'съм': 'I am',
  'си': 'are (you) / yourself',
  'добро': 'good (neuter)',
  'утро': 'morning',
  'добър': 'good (masc)',
  'ден': 'day',
  'вечер': 'evening',
  'лека': 'light / gentle',
  'нощ': 'night',
  'казваш': 'you are called',
  'казвам': 'I am called',
  'се': '(reflexive particle)',
  'приятно': 'pleasant / nice',
  'ми': 'to me',
  'моля': 'please / you\'re welcome',
  'благодаря': 'thank you',
  'извинете': 'excuse me',
  'съжалявам': 'I\'m sorry',

  // Town & places
  'хотел': 'hotel',
  'хотелът': 'the hotel',
  'ресторант': 'restaurant',
  'ресторантът': 'the restaurant',
  'магазин': 'shop / store',
  'аптека': 'pharmacy',
  'аптеката': 'the pharmacy',
  'болница': 'hospital',
  'болницата': 'the hospital',
  'банка': 'bank',
  'гара': 'train station',
  'автобус': 'bus',
  'автобусът': 'the bus',
  'метро': 'metro / subway',
  'метрото': 'the metro',
  'такси': 'taxi',
  'спирка': 'bus stop',
  'билет': 'ticket',
  'билетът': 'the ticket',
  'билети': 'tickets',
  'вляво': 'to the left',
  'вдясно': 'to the right',
  'направо': 'straight ahead',
  'близо': 'near / close',
  'далеч': 'far',
  'има': 'there is',
  'стигна': 'reach / get to',
  'струва': 'costs',
  'имате': 'you have',
  'имате ли': 'do you have',
  'Вземете': 'take',
  'вземете': 'take',
  'имам': 'I have',
  'нямам': "I don't have",
  'искам': 'I want',

  // Food & drink
  'вода': 'water',
  'кафе': 'coffee',
  'кафета': 'coffees',
  'чай': 'tea',
  'бира': 'beer',
  'вино': 'wine',
  'сок': 'juice',
  'хляб': 'bread',
  'месо': 'meat',
  'риба': 'fish',
  'салата': 'salad',
  'супа': 'soup',
  'десерт': 'dessert',
  'бих': 'I would',
  'искал': 'like (masc)',
  'искала': 'like (fem)',
  'сметката': 'the bill',
  'вкусно': 'delicious',

  // Numbers 1–10
  'едно': 'one',
  'две': 'two',
  'три': 'three',
  'четири': 'four',
  'пет': 'five',
  'шест': 'six',
  'седем': 'seven',
  'осем': 'eight',
  'девет': 'nine',
  'десет': 'ten',

  // Family
  'майка': 'mother',
  'баща': 'father',
  'брат': 'brother',
  'сестра': 'sister',
  'сестри': 'sisters',
  'дете': 'child',
  'деца': 'children',
  'дядо': 'grandfather',
  'баба': 'grandmother',
  'съпруг': 'husband',
  'съпруга': 'wife',
  'семейство': 'family',
  'голям': 'big (masc)',
  'голяма': 'big (fem)',
  'голямо': 'big (neuter)',
  'малък': 'small (masc)',
  'малка': 'small (fem)',
  'стар': 'old (masc)',
  'стара': 'old (fem)',
  'старо': 'old (neuter)',
  'млад': 'young (masc)',
  'млада': 'young (fem)',
  'младо': 'young (neuter)',
  'хубав': 'nice / beautiful (masc)',
  'хубава': 'nice / beautiful (fem)',
  'хубаво': 'nice / beautiful (neuter)',
  'моят': 'my (masc)',
  'моята': 'my (fem)',
  'моето': 'my (neuter)',
  'нямам': "I don't have",

  // School
  'училище': 'school',
  'клас': 'class / classroom',
  'учител': 'teacher (m)',
  'учителка': 'teacher (f)',
  'учителката': 'the teacher (f)',
  'ученик': 'student (m)',
  'ученичка': 'student (f)',
  'книга': 'book',
  'книги': 'books',
  'тетрадка': 'notebook',
  'молив': 'pencil',
  'химикал': 'pen',
  'раница': 'backpack',
  'раницата': 'the backpack',
  'дъска': 'blackboard',
  'разбирам': 'I understand',
  'урока': 'the lesson',
  'повторете': 'please repeat',
  'помощ': 'help',
  'дава': 'gives',

  // Days of the week
  'понеделник': 'Monday',
  'вторник': 'Tuesday',
  'сряда': 'Wednesday',
  'четвъртък': 'Thursday',
  'петък': 'Friday',
  'събота': 'Saturday',
  'неделя': 'Sunday',
}
